Upgrade to Java 21
companieshouse/account-validator-api pull request #32
Opened 2024-07-08 12:49 UTC by vshastri-ch

2024-07-08 12:57 UTC, foman-ch requested changes

2024-07-08 12:57 UTC, foman-ch commented on pom.xml
> +        <version>2.1.5</version>
think there's now a 2.1.6 version

2024-07-08 12:57 UTC, foman-ch commented on pom.xml
> +        <spring-boot-dependencies.version>3.3.0</spring-boot-dependencies.version>
there's now a 3.3.1 version of Spring Boot

2024-07-08 13:00 UTC, dgurjar-ch commented on src/main/java/uk/gov/companieshouse/account/validator/security/WebSecurityConfig.java
> +    WebSecurityCustomizer ignoringCustomizer() {
I think , actual healthCheck end point needs to be configure.

2024-07-09 12:07 UTC, foman-ch approved these changes

2024-07-09 12:12 UTC, dgurjar-ch commented on src/main/resources/application.properties
> +management.endpoints.web.path-mapping.health=/account-validator/validate/healthcheck
I think path don't need two / , Please remove one  backslash(/) .

2024-07-10 09:16 UTC, dgurjar-ch approved these changes

2024-07-10 09:17 UTC, merged